### ISSUE TITLE
STDOUT instructions / capability

### ISSUE THREAD

**Issue by binarylogic** [timberio/timber-js#42]
How would one go about using the Timber library to write to `STDOUT` instead of shipping logs over HTTP? This is necessary for more complex setups that want to write to `STDOUT` and then forward that data external from their app.

This is, of course, specific to Node only.

**Comment by leebenson** [comment]
There are two approaches that could be taken to write to `STDOUT`, depending on whether you _first_ want the logs to hit Timber.io, or whether you want to avoid hitting Timber altogether and _just_ display to STDOUT:

**1. Log at Timber.io, _then_ -> `STDOUT`**

The easiest way is to use built-in [streaming](https://github.com/timberio/timber-js/tree/master/packages/node#streaming) features, by calling `.pipe()`

```ts
const timber = new Timber("api-key-here");
timber.pipe(process.stdout); // <-- this will send a copy to `STDOUT`

timber.log("This will also show up in the console...");
```

The format that will dumped to STDOUT is a JSON serialized version, e.g.:

```
{"dt":"2019-03-09T14:08:03.963Z","level":"info","message":"This will also show up in the console..."}
```

**2. Avoid logging to Timber.io _at all_, and go totally custom**

You can create your own 'sync' method which takes a batch of logs, and does whatever you want with it -- overriding the default (which is to sync to Timber.io)

An example is shown in the [`@timberio/core` docs](https://github.com/timberio/timber-js/tree/master/packages/core#the-base-class)

For example, to avoid syncing and just dump all logs out to the console...

```ts
const timber = new Timber("api-key-here");
timber.setSync(async logs => {
    logs.forEach(log => console.log(`Log: ${log}`));
    return logs;
})
```

Both use-cases are covered by examples in the docs, although they aren't specific to `STDOUT` - they can be used with _any_ streaming interface, such as file/network I/O, etc.

**Comment by binarylogic** [comment]
Nice, this is great. Thanks!

**Comment by binarylogic** [comment]
@leebenson can you confirm that the above `STDOUT` example will write the logs in JSON format? I'm pretty sure that's the case but wanted to confirm.

**Comment by leebenson** [comment]
The first example will do that automatically, yup:

> The format that will dumped to STDOUT is a JSON serialized version, e.g.:
>
> {"dt":"2019-03-09T14:08:03.963Z","level":"info","message":"This will also show up in the console..."}

That's because [this line](https://github.com/timberio/timber-js/blob/master/packages/node/src/node.ts#L79) automatically `JSON.serialize()`s the log to a string before passing it to a writable stream - so _any_ writable stream (process.stdout, network/file I/O, etc) will receive the data as a JSON string and _not_ the original `ITimberLog` object.

In the second example, the function we pass to `.setSync` will receive the raw `logs` array (an array of `ITimberLog` objects), so we can do whatever we want with the data - console.log it, JSON.serialize(), save it to a DB, etc. In the above example, I'm just logging it out to the console, which _won't_ be JSON (it'll just be a formatted JS object); if we want serialize it, we could just wrap the raw log in `JSON.serialize()` a la the `.pipe()` method:

```ts
const timber = new Timber("api-key-here");
timber.setSync(async logs => {
    logs.forEach(log => console.log(`Log: ${JSON.serialize(log)}`));
    return logs;
});
```
