### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by danielvaijk** [timberio/timber-js#43]
This happened a few weeks ago and then stopped. Today Sentry captured the exception once again and I'm wondering what exactly it means and what causes it.

Error was thrown from @timberio/node/dist/cjs/node.js at line 37:

            /**
             * TODO: if status is 50x throw custom ServerError
             * to be used in retry logic
             */
            throw new Error(res.statusText);

**Comment by binarylogic** [comment]
@leebenson this probably shouldn't throw an error. What are our alternatives? Ideally, our clients would retry delivery 3 times and then drop the payload if delivery fails.

**Comment by leebenson** [comment]
The error is thrown if there was a network or server failure connecting to Timber.io.

Since all logging in TimberJS is handled using Promises, this will result in a 'rejected' promise on the original `.log|info|debug|warn|error` method.

This is by design, and models how Promises work with `fetch()` and regular Javascript Promise semantics; whenever there's a network or failure of some kind, the Promise rejects. This allows you to 'catch' the problem and handle it in some way -- typically by either retrying, logging out to the console, or some other logic that's suitable for your app.

This prevents logging from failing silently without offering a mechanism to handle it in your app code.

Here's an example of how you might catch a particular failed log:

```ts
t.info("Order #1234 placed, total: $500.23", {
  order_placed: {
    id: 1234,
    total: 500.23,
  },
}).catch(error => {
  console.log(`ERROR: Couldn't log order to Timber: ${error}`);
});
```

If you were operating inside of an async function, you could instead use async JS flow:

```ts
try {
  await t.info("Order #1234 placed, total: $500.23", {
    order_placed: {
      id: 1234,
      total: 500.23,
    },
  })
} catch (error) {
  console.log(`ERROR: Couldn't log order to Timber: ${error}`);
}
```

If you prefer to ignore exceptions and avoid dealing with them in app code altogether, then in [v0.32.0](https://github.com/timberio/timber-js/releases/tag/v0.32.0) you can pass a new `ignoreExceptions` option to `Timber` class instantiation which will swallow all exceptions.

Use it like this:

```ts
const timber = new Timber("your-api-key", {
    ignoreExceptions: true
});
```

This will prefer exceptions bubbling up to a Promise reject, so you won't have to supply any `.catch()` handler (or `try/catch` wrapper) if you're not concerned with being notified on errors.

Let me know if you run into any issues or have any questions!
